// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fekywrlqcnscfpmfysfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZla3l3cmxxY25zY2ZwbWZ5c2Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzI4ODIsImV4cCI6MjA2NDA0ODg4Mn0.yNJULPrUYvBsfWjV5qpDRqF8lD3og6nYJr6VAiPDrO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);